# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Cobbled"
title_separator          : "-"
name                     : "Joshua G. Ortiz Baco"
description              : "Look, a thing I made."
url                      : "https://joshuagob.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  :  # the subpath of your site, e.g. "/blog"
repository               : "joshuagob/joshuagob.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/favicon/ms-icon-310x310.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment."
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : "jgob"
facebook:
  username               : "otroadoquin"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : "Joshua G. Ortiz Baco" # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.facebook.com/otroadoquin"
    - "https://www.github.com/joshuagob"
    - "https://www.twitter.com/jgob"
# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Joshua G. Ortiz Baco"
  avatar           : "/assets/images/favicon.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am person."
  location         : "Somewhere"
  email            : "joshuaortizbaco@utexas.edu"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "otroadoquin"
  foursquare       :
  github           : "joshuagob"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : "jgob"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

#responsive plugin
# responsive_image:
#   template: _includes/srcset.html
# Reading Files
include:
  - .htaccess
  - _pages
  - home
  - _posts
  - year-archive
  - categories-archive
  - map
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-twitter-plugin

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-twitter-plugin

#Tweetsert is a plugin for Jekyll that pulls recent tweets from one or more Twitter handles,
#then inserts them (dated appropriately) as regular posts on your site. You can specify which
#tweets to include or exclude based on patterns or words, import retweets and replies, and tweak
#the theme and link colors of the embedded tweet.To organize your tweet-posts, Tweetsert can automatically assign a category and/or tag. You may also choose to automatically import Twitter hashtags.

tweetsert:
  enabled: true
  layout: "tag" # Template in _layouts to use; default "page"

  # Show additional messages for debugging
  #debug: true

  # Prefix, number of words, and suffix of the generated titles
  title:
    #prefix: "[Tweet] "
    words:  9
    suffix: " ..."

  # Some post/page properties you may want to set automatically
  #properties:
  #  is_tweet: true
  #  tweet_html: $    # the embedded tweet
  #  share: false
  #  comments: true

  # The timeline(s) you import, and which tweets you want/don't want
  timeline:
    # Your handle; you may also just use 'handles' below
    #handle:

    # Other handles you want to include
    # If you get an 404 Not Found, you may have misspelled a handle
    handles:
      - 'pringangstmosa'
      - 'jgob'

    # The token you got via tweetsert.hook.io
    # You may also use the JTP_ACCESS_TOKEN environment variable instead
    access_token: "42070947-9yogo8Zj980acVYmrB2O1mKSulbFfJfjvlMJASHdL"

    # Timeline entries to retrieve. Limited by Twitter to 200; default 100
    # Note that this includes deleted tweets, so it's not exact
    limit: 100

    # Include tweets starting with @handle; default: false
    replies: true

    # Include retweets (RT); default false
    retweets: true

    # If both include and exclude are configured below,
    # only tweets pulled in by "include" will be further filtered by "exclude"

    # Only include tweets that have these words/handles/hashtags/URLs
    #  (case insensitive regex)
    #include:
      #- '#blog'
      #- '(^|[^@\w])@(\w{1,15})\b'  # Must mention @someone
      #- 'important'
      #- '@handle'

    # Exclude tweets that have these words/handles/hashtags/URLs
    #   (case insensitive regex)
    exclude:
      - 'https://joshuagob.github.io\d+/'  # Your own blog posts
      #- '^.@'                       # Tweets that start with .@someone
      #- 'ignore'
      #- '#somehash'
      #- '@handle'

    # Do not include tweets newer than your latest post; default true
    #no_newer: false

    # Do not include tweets older than your first post; default true
    #no_older: false

  embed:
    # Set to false if you don't want the excerpt to be set; default true
    #excerpts: false

    # Set to dark if you want a dark background/light text; default: light
    #theme: "dark"

    # Base color of the links, default: set by Twitter
    #link_color: "#80FF80"

    # Include Twitter's oEmbed API script every time; default: false
    # Set to true if you manually include it in e.g. the header
    #omit_script: true

    # Some markup to include right before and after the embedded tweet
    # {{anything}} will be expanded to the corresponding frontmatter/properties
    #prefix: '<i>This was tweeted on {{date}}</i>'
    #suffix: '<i>This is after. Click <a href="{{url}}">here</a> to view this tweet separately.</i>'

  category:
    default: "tweets"                  # Automatically set to this category
    dir: "categories-archive"                            # Folder that contains your categories
    #dir: "categories"                 # Default

    layout: "categories"                # What layout to use, inside _layouts
    #layout: "category_index"          # Default

    #title:
    #  prefix: "Posts in the &laquo;"  # Prefix of the generated title
    #  suffix: "&raquo; category"      # Suffix of the generated title

  tags:
    #default: "tweet"                  # Tag all tweets automatically with this
    dir: "tag"                         # Location of the generated tag indices
    layout: "tags"                #  As above, for tags
    #title:
    #  prefix: "Posts tagged &ldquo;"
    #  suffix: "&rdquo;"

    hashtags: true                     # Import #hashtags as site tags

    # Hashtags you don't want to import
    ignore:
      - blahblah

    # Automatic tagging based on content, tag: <string or array>
    #auto:
    #  keepkey: "@bitcoinkeepkey"
    #  ethereum: "ethereum"
    #  pets:
    #    - buzzfeedanimals
    #    - Duchess
    #    - Princess
    #    - Athos

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
